version: '3.4'

services:
  spendingssummary.fileprocessor:
    image: spendingssummaryfileprocessor
    container_name: 'spendingssummary.fileprocessor'
    build:
      context: .
      dockerfile: ImportedReports/ImportedReports.WorkerService/Dockerfile
    volumes:
      - "imported-files:/${ImportSettings__ReportFilesFolder}"
    depends_on:
      - spendingssummary.db
      - spendingssummary.rabbitmq
    networks:
        - queue-net
  
  spendingssummary.db:
    image: mcr.microsoft.com/mssql/server
    container_name: 'spendingssummary.db'
    environment:
      SA_PASSWORD: "${DataBaseSettings__SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:  
      - "1433:${DataBaseSettings__Port}"
    volumes:
      - "db-data:/var/opt/mssql/" 
    networks:
        - queue-net

  spendingssummary.rabbitmq:
    image: spendingssummaryqueue
    container_name: 'spendingssummary.rabbitmq'
    build:
      context: .
      dockerfile: Common/Rabbitmq/Dockerfile
    ports:
        - 5672:${RaddisQueueSettings__Port}
        - 15672:15672
    volumes:
        - rabbit-data:/var/lib/rabbitmq/
        - rabbit-logs:/var/log/rabbitmq/
        - rabbit-conf:/etc/rabbitmq/
    networks:
        - queue-net
  spendingssummary.fileupload:
    image: ${DOCKER_REGISTRY-}spendingssummaryfileupload
    build:
      context: .
      dockerfile: FileUpload/SpendingsSummary.FileUpload.Presentation/Dockerfile

volumes:
  db-data:
  rabbit-data:
  rabbit-logs:
  imported-files:
  rabbit-conf:
networks:
  queue-net:
    driver: bridge

